### ISSUE TITLE
List of offensive words?

### ISSUE THREAD

**Issue by subbob** [Gwindalmir/SEChatFilterPlugin#1]
Where and how do you define the offensive language to be censored?

**Comment by Gwindalmir** [comment]
It's provided by the game itself.
This plugin does not provide a list, nor provide access to change the list.
You can find it at: **<Steam Install/Library>\SteamApps\common\SpaceEngineers\Content\Data\OffensiveWords.sbc**.

**Comment by subbob** [comment]
> It's provided by the game itself. This plugin does not provide a list, nor provide access to change the list. You can find it at: **<Steam Install/Library>\SteamApps\common\SpaceEngineers\Content\Data\OffensiveWords.sbc**.

I see, thank you for the quick response.
